services:
  - type: web
    name: numeron-game
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: INFO
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: MAX_TURNS
        value: "12"
      - key: NUMBER_LENGTH
        value: "3"
